diffusion_lddt_chunk_size: 1
diffusion_bond_chunk_size: 1
diffusion_sparse_loss_enable: ${exp.model.loss_metrics_sparse_enable}
diffusion_lddt_loss_dense: true

resolution:
  min: 0.1
  max: 4.0

weight:
  alpha_diffusion: 4.0
  alpha_distogram: 3e-2
  alpha_bond: 1.0
  smooth_lddt: 1.0
  alpha_bond_type: 1.0

diffusion:
  bond:
    eps: 1e-6
  mse:
    eps: 1e-6
    weight_dna: 5.0
    weight_ligand: 10.0
    weight_mse: ${eval:'1/3'}
    weight_rna: 5.0
  smooth_lddt:
    eps: 1e-6

distogram:
  eps: 1e-6
  max_bin: 21.6875
  min_bin: 2.3125
  no_bins: 64

bond_type:
  alpha: 1.0
  eps: 1e-6
  k: 2.0
  num_classes: 2